//
// made by Julius Gerhardus
//
// for Gymnasium Haan / IT lectures
//
// This is an almost 1 to 1 copy of the Sydney Opera House in Sydney. Some things are not possible
// due to the limitations of OpenSCAD (thats why the Ocean is generated by a Python script.
//
// IMPORTANT!!!
// 
// This has to be viewed in Orthogonal Render or there will be some weird lag with the difference()
// function.
//
// Also it is highly recommended to use the newest version of OpenSCAD for minimum lag!
//
// References:
// 
// https://en.wikipedia.org/wiki/Sydney_Opera_House
// -> some google images as well
//
// Tweaks:
$fn=50;
//
// ^^ renders with a standard of "50" faces per object
//
lagfree=false;
//
// ^^ removes fills of stairs to remove some lag
//
// Private variables DO NOT CHANGE:
s1m=3.1; //multiplier for the shells
buffer=0.99; //universial 
buffer2=1.5; //buffer for the shell depth
radiuss1=10; //radius for the first shell
radiuss2=10; //radius for the second shell
radius=10;
//
// Hex Color codes:
color="#758C7C";
color2="#B6BCBD";
//
// include the Ocean here (the file is to large to import directly) NOT RECCOMENDED DUE TO LAG
include <ocean.scad>
//
ocean(); //spawn the ocean (change parameters in file)
//
// Modules:
module shell1(radius) { // Renders a shell
    difference() {
        balls(radius);
        translate([0,0,-11]) 
            cube([20,20,15], center = true);
        translate([-10*s1m+5,0,-10])
            sphere(r=radius*s1m);
    }      
}
module cutout(radius) { //cutout to make the shell hollow
    color(color) {
        scale([0.9,0.9,0.9]) translate([6.5,0,0]) {
            intersection() {
                translate([-10*s1m,0,-10])
                    sphere(r=10*s1m);
                translate([-7,0,0])
                    shell1(radiuss2);
            }
        }
    }
}
module balls(ra) { //renders 2 balls in an intersection
    color(color2)
    intersection() {
            translate([0,ra / 2,0])
                sphere(r=ra);
            translate([0,-ra / 2,0])
                sphere(r=ra);
        }
}
module transition() {
    scale([0.39,0.39,0.39]) rotate([20,-5,30]) translate([-8,6,-18])
        union() {
            difference() {
                difference() {
                    sphere(20);
                    sphere(20-2);
                }
                rotate([0,0,45]) translate([-20,0,-20])
                    cube([40,40,40]);
                translate([0,-20,-20])
                    cube([40,40,40]);
                difference() {
                    sphere(30);
                    translate([-40,-40,10])
                        cube([80,80,80]);
                }
                translate([0,0,0])
                    cube([15,15,15]);
            }
        }
}
module f1inside(x) {
    translate([x,2.15,-1.5]) rotate([0,0,-15])
        cube([2,5,5], center=true);
    translate([x,-2.15,-1.5]) rotate([0,0,15])
        cube([2,5,5], center=true);
}
module f2inside(x) {
    translate([-1.7,0,-5.2]) rotate([0,45,0]) {
        translate([x,1.3,-1.5]) rotate([0,0,-15])
            cube([2,3.25,2], center=true);
        translate([x,-1.3,-1.5]) rotate([0,0,15])
            cube([2,3.25,2], center=true);
    }
    difference() {
        translate([x+15.6,0,2.1]) rotate([0,-15,0]) {
            difference() {
                cylinder(r=20, h=1, $fn=100);
                translate([x+10,0,0.5])
                    cube([40,42,1.6], center=true);
                translate([x-13,10,0.5]) rotate([0,0,120])
                    cube([10,10,1.6], center=true);
                translate([x-7.26,7,0.5]) rotate([0,0,20])
                    cube([10,10,1.6], center=true);
                mirror([0,1,0]) {
                    translate([x-13,10,0.5]) rotate([0,0,120])
                        cube([10,10,1.6], center=true);
                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                        cube([10,10,1.6], center=true);
                }
            }
        }
        translate([-10,-5.8,-3.8]) rotate([20,0,-7.5]) {
            color("#B8A693") cube([4,2,2]);
        }
        mirror([0,1,0]) {
            translate([-10,-5.8,-3.8]) rotate([20,0,-7.5]) {
                color("#B8A693") cube([4,2,2]);
            }
        }
    }
}
module binside(x) {
    translate([x-0.5,-1,-4]) rotate([0,0,-5])
        color(color) cube([2,5,6]);
    translate([x,-5.5,-4]) rotate([0,-10,-5])
        color(color) cube([2,5,6]);
    translate([11.8,2,-3.25]) rotate([0,-90,85]) //triangle roof thingy -> transition
        color("#B8A693")
        linear_extrude(height=2.5)
            circle(r=0.5, $fn=3);
}
module binside_second_hall(x) {
    translate([x+0.9,0,-4]) rotate([0,-10,10])
        color(color) cube([2,5,6]);
    translate([x,-4.3,-4]) rotate([0,-10,-10])
        color(color) cube([2,5,6]);
    translate([13.23,-2.5,-3.277]) rotate([-90,0,10]) //triangle roof thingy -> transition
        color("#B8A693")
        linear_extrude(height=2.5)
            circle(r=0.5, $fn=3);
    translate([x+1,-2.9,-2.94]) rotate([0,0,10])
        color("#B8A693") cube([2,2.5,0.1]);
}
module h3inside() { //hall 3 inside
    difference() {
        translate([14.7,-2,-3.5]) rotate([0,0,0])
            color(color) cylinder(h=1, r=1.3, $fn=100);
        translate([14.8,-4.5,-3.6]) cube([2,5,2]);
        color(color) translate([14.7,-1.8,-3.55]) {
            difference() {
                sphere(r=1.7);
                sphere(r=1.7-0.4);
                translate([-2,-2,-2]) cube([4,4,2]);
            }
        }
        color(color) translate([14.7,-2.2,-3.55]) {
            difference() {
                sphere(r=1.7);
                sphere(r=1.7-0.4);
                translate([-2,-2,-2]) cube([4,4,2]);
            }
        }
        translate([12,-4,-5.3]) cube([4,4,2]);
    }
    rotate([0,180,180]) translate([0,4,6.6]) {
        difference() {
            translate([14.7,-2,-3.5]) rotate([0,0,0])
                color(color) cylinder(h=1, r=1.3, $fn=100);
            translate([14.8,-4.5,-3.6]) cube([2,5,2]);
            color(color) translate([14.7,-1.8,-3.55]) {
                difference() {
                    sphere(r=1.7);
                    sphere(r=1.7-0.4);
                    translate([-2,-2,-2]) cube([4,4,2]);
                }
            }
            color(color) translate([14.7,-2.2,-3.55]) {
                difference() {
                    sphere(r=1.7);
                    sphere(r=1.7-0.4);
                    translate([-2,-2,-2]) cube([4,4,2]);
                }
            }
            translate([12,-4,-5.3]) cube([4,4,2]);  
        }
    }
}
module roof() {
    difference() { //first shell
        color(color2) shell1(radiuss1);
        cutout(radiuss1-0.75);
        mirror([0,1,0]) {
            cutout(radiuss1-0.75);
        }
    }
    translate([-4,0,-3.4]) rotate([0,-2.5,0])
        difference() { //second shell
            color(color2) shell1(radiuss2);
            cutout(radiuss1-0.75);
            mirror([0,1,0]) {
                cutout(radiuss1-0.75);
            }
        }
    translate([-7.5,0,-6.5]) rotate([0,-5,0])
        difference() { //third shell
            color(color2) shell1(radiuss2);
            translate([0.79,0,0]) {
                cutout(radiuss1-0.75);
                mirror([0,1,0]) {
                    cutout(radiuss1-0.75);
                }
            }
        }
    translate([14,0,-6]) rotate([0,-5,180]) scale([1,0.8,1])
        difference() { //back shell (from biggest shell)
            color(color2) shell1(radiuss2);
            scale([0.9,0.9,0.9])
                balls(10);
        }
    scale([1,0.8,1]) translate([7.2,0,-2]) rotate([0,5,0])
            difference() { //first transition from biggest to middle shell / inside
                color(color2) mirror([1,0,0]) shell1(radiuss2);
                translate([4,0,4])
                    cube([13,13,13], center=true);  
            }
    scale([1,0.8,1]) translate([2,0,-5]) rotate([0,5,0])
            difference() { //second transition from middle to smallest shell / inside
                color(color2) mirror([1,0,0]) shell1(radiuss2);
                translate([4,0,4])
                    cube([13,13,13], center=true);  
            }
    color(color2) transition();              //transition bottom shell / sides
    mirror([0,1,0])  {                         
        color(color2) transition();
    }
    scale([1,1,1.25]) translate([5,-0.4,0]) { //transition top shell / sides
        translate([-0.1,0.3,1.5]) rotate([10,-3,6])
            color(color2) transition();
        mirror([0,1,0]) {
            translate([-0.1,-0.3,1.5]) rotate([10,-3,6]) 
                color(color2) transition();
       }
    }
    translate([10,0,-1]) {
        rotate([-15,20,-20]) translate([1,-1,-0.5]) scale([0.7,0.7,1]) {
            color(color2) transition();     //transition back shell left / sides
        }
        rotate([-5,-5,0]) translate([1.4,-0.7,0]) scale([0.7,0.7,1]) {
            color(color2) transition();     //transition back shell left/ sides
        }
    }
    translate([10,0,-1]) mirror([0,1,0]) {
        rotate([-15,20,-20]) translate([1,-1,-0.5]) scale([0.7,0.7,1]) {
            color(color2) transition();     //transition back shell right / sides
        }
        rotate([-5,-5,0]) translate([1.4,-0.7,0]) scale([0.7,0.7,1]) {
            color(color2) transition();     //transition back shell right/ sides
        }
    }
    color(color) {
        translate([0.5,0,0]) {
            intersection() {  //front shell inside
                translate([-8.5,0,-6]) scale([0.89,0.89,0.89])
                    balls(10);
                    f1inside(-6);
            }
            f2inside(-6);
        }
    }
}
module triangle() { //front triangle roof thingy
    color("#B8A693") intersection() {
        scale([0.1,0.1,0.1]) translate([790/4-46,105/4,-66/4-21.5]) rotate([0,0,7.5]) {
            rotate_extrude(angle=360, $fn=1000) {
                rotate([0, 0, 0]) {
                    translate([250,0,0])
                    polygon(points=[[0, 0], [1, 0], [0, 1]]);
                }
            }
        }
        translate([-10,-5.75,-4]) rotate([0,0,7.5])
            cube([2,7.99,1]);
    }
}
module fence() { //fence
    translate([-1.8,4,-3])
    color("gray")
        for(i=[0:0.1:5.9]) {
            translate([0,i/2,0])
                cube([0.01,0.01,0.4]);
        }
    color("gray")
        translate([-1.8,4,-2.8]) cube([0.025,3,0.025]); 
}
module ohall() { //outside hall way
    translate([5,-5.4,-4]) {
        color("#B8A693") cube([7.9,1,0.1]);
        translate([0.1,0,-1]) {
            for(i = [0:1:8]) {
                translate([i/1.05,0,0]) color("#C0C0C0") cube([0.1,0.1,1]);
            }
        }
        translate([0.1,0.8,-1]) {
            for(i = [0:1:8]) {
                translate([i/1.05,0,0]) color("#C0C0C0") cube([0.1,0.1,1]);
            }
        }
    }
}
module bottom(x, depth) { //front bottom thingy
    difference() {
        translate([0,0,-8.5]) rotate([0,0,0]) color("#B8A693"){ // top floor
            translate([2.5,0,4.3]) rotate([0,15,0])
                cube([2, 10, 2], center=true);
                translate([-0.2,0,4.525]) rotate([0,0,0])
                    cube([4, 10, 2], center=true);
            difference() {
                union() {
                    translate([-2.9,0,5]) rotate([0,15,0])
                        cube([3.5, 10, 2], center=true);
                    translate([-5.825,0,5.425]) rotate([0,0,0])
                        cube([3, 10, 2], center=true);
                    translate([-7.35,-5,3])
                        cube([12,10,2]);
                }
                translate([-8,-6.3,2.5]) rotate([0,0,-7.5]) 
                    cube([7.5,2,4]);
                translate([-8,4.25,2.5]) rotate([0,0,7.5]) 
                    cube([7.5,2,4]);        
            }
        }
        translate([-2.2,-5.1,-4.1]) color(color) cube([4.6,0.15,0.1]); //window 3
        translate([-3.7,-4.9,-4.1]) rotate([0,0,-7.5]) color(color) cube([1,0.15,0.1]); //window 4
        translate([1.15,-5.9,-5.2]) rotate([0,0,0]) color(color) cube([1,1,1]); //entrance
    }
    translate([1.15,-5,-4.45]) rotate([0,90,0]) color("#B8A693") //entrance
            linear_extrude(height=1)
                rotate([0,0,-60]) circle(r=0.25, $fn=3);
    translate([0,-0.01,-1]) { // top floor
        difference() {
            translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                color("#B8A693") difference() {
                    cylinder(r=20, h=2, $fn=100);
                    translate([x+10,0,1])
                        cube([40,42,4], center=true);
                    translate([x-13,10,0.5]) rotate([0,0,120])
                        cube([10,10,4], center=true);
                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                        cube([10,10,4], center=true);
                    mirror([0,1,0]) {
                        translate([x-13,10,0.5]) rotate([0,0,120])
                            cube([10,10,4], center=true);
                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                            cube([10,10,4], center=true);
                    }
                }
            }
            
            translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                color("#B8A693") cube([4,2,4]);
            }
            mirror([0,1,0]) {
                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([4,2,4]);
                }
            }
            translate([-0.1,0,1.9]) scale([0.9,0.9,0.9]){
                difference() { // top green inside
                    translate([0,-0.01,-3.1]) scale([1.1,1.125,1]) {
                        difference() {
                            translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                                color(color) difference() {
                                    cylinder(r=20, h=2, $fn=100);
                                    translate([x+10,0,1])
                                        cube([40,42,4], center=true);
                                    translate([x-13,10,0.5]) rotate([0,0,120])
                                        cube([10,10,4], center=true);
                                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                                        cube([10,10,4], center=true);
                                    mirror([0,1,0]) {
                                        translate([x-13,10,0.5]) rotate([0,0,120])
                                            cube([10,10,4], center=true);
                                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                                            cube([10,10,4], center=true);
                                    }
                                }
                            }
                            
                            translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                color(color) cube([4,2,4]);
                            }
                            mirror([0,1,0]) {
                                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                    color(color) cube([4,2,4]);
                                }
                            }
                        }
                    }
                    translate([0.2,-0.01,-2.8]) scale([1.1,1.125,1]) {
                        difference() {
                            translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                                color(color) difference() {
                                    cylinder(r=20, h=2, $fn=100);
                                    translate([x+10,0,1])
                                        cube([40,42,4], center=true);
                                    translate([x-13,10,0.5]) rotate([0,0,120])
                                        cube([10,10,4], center=true);
                                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                                        cube([10,10,4], center=true);
                                    mirror([0,1,0]) {
                                        translate([x-13,10,0.5]) rotate([0,0,120])
                                            cube([10,10,4], center=true);
                                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                                            cube([10,10,4], center=true);
                                    }
                                }
                            }
                            
                            translate([-10,-5.25,-5]) rotate([0,0,-7.5]) {
                                color(color) cube([4,2,4]);
                            }
                            mirror([0,1,0]) {
                                translate([-10,-5.25,-5]) rotate([0,0,-7.5]) {
                                    color(color) cube([4,2,4]);
                                }
                            }
                        }
                    }
                    
                    translate([-11,4,-6]) rotate([0,0,0])
                        color("#B8A693") cube([5,5,5]);
                    mirror([0,1,0]) {
                        translate([-11,4,-6]) rotate([0,0,0]) {
                            color("#B8A693") cube([5,5,5]);
                        }
                    }
                }
            }
        }
    }
    difference() { //middle cutout
        translate([0.5,-0.01,-1.75]) scale([1.1,1.1,1.1]) {
            difference() {
                translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                    color("#B8A693") difference() {
                        cylinder(r=20, h=2, $fn=100);
                        translate([x+10,0,1])
                            cube([40,42,4], center=true);
                        translate([x-13,10,0.5]) rotate([0,0,120])
                            cube([10,10,4], center=true);
                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                            cube([10,10,4], center=true);
                        mirror([0,1,0]) {
                            translate([x-13,10,0.5]) rotate([0,0,120])
                                cube([10,10,4], center=true);
                            translate([x-7.26,7,0.5]) rotate([0,0,20])
                                cube([10,10,4], center=true);
                        }
                    }
                }
                
                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([4,2,4]);
                }
                mirror([0,1,0]) {
                    translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                        color("#B8A693") cube([4,2,4]);
                    }
                }
            }
        }
        translate([0.575,-0.01,-0.1]) scale([1.1,1.06,1]) {
            difference() {
                translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                    color("#B8A693") difference() {
                        cylinder(r=20, h=2, $fn=100);
                        translate([x+10,0,1])
                            cube([40,42,4], center=true);
                        translate([x-13,10,0.5]) rotate([0,0,120])
                            cube([10,10,4], center=true);
                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                            cube([10,10,4], center=true);
                        mirror([0,1,0]) {
                            translate([x-13,10,0.5]) rotate([0,0,120])
                                cube([10,10,4], center=true);
                            translate([x-7.26,7,0.5]) rotate([0,0,20])
                                cube([10,10,4], center=true);
                        }
                    }
                }
                
                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([4,2,4]);
                }
                mirror([0,1,0]) {
                    translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                        color("#B8A693") cube([4,2,4]);
                    }
                }
            }
        }
        translate([-8.5,-4.56,-3.4]) rotate([0,25,-7.5]) {
            color("#B8A693") cube([2,0.4,0.9]);
        }
        translate([-8.5,-4.8,-3.3]) rotate([0,25,-7.5]) {
            color("#B8A693") cube([2,0.4,0.9]);
        }
        mirror([0,1,0]) {
            translate([-8.5,-4.56,-3.4]) rotate([0,25,-7.5]) {
                color("#B8A693") cube([2,0.4,0.9]);
            }
            translate([-8.5,-4.8,-3.3]) rotate([0,25,-7.5]) {
                color("#B8A693") cube([2,0.4,0.9]);
            }
        }
        translate([0.5,0,0.8]) {
            difference() { // middle green inside
                translate([0,-0.01,-3.1]) scale([1.1,1.125,1]) {
                    difference() {
                        translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                            color(color) difference() {
                                cylinder(r=20, h=2, $fn=100);
                                translate([x+10,0,1])
                                    cube([40,42,4], center=true);
                                translate([x-13,10,0.5]) rotate([0,0,120])
                                    cube([10,10,4], center=true);
                                translate([x-7.26,7,0.5]) rotate([0,0,20])
                                    cube([10,10,4], center=true);
                                mirror([0,1,0]) {
                                    translate([x-13,10,0.5]) rotate([0,0,120])
                                        cube([10,10,4], center=true);
                                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                                        cube([10,10,4], center=true);
                                }
                            }
                        }
                        
                        translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                            color(color) cube([4,2,4]);
                        }
                        mirror([0,1,0]) {
                            translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                color(color) cube([4,2,4]);
                            }
                        }
                    }
                }
                translate([0.2,-0.01,-2.8]) scale([1.1,1.125,1]) {
                    difference() {
                        translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                            color(color) difference() {
                                cylinder(r=20, h=2, $fn=100);
                                translate([x+10,0,1])
                                    cube([40,42,4], center=true);
                                translate([x-13,10,0.5]) rotate([0,0,120])
                                    cube([10,10,4], center=true);
                                translate([x-7.26,7,0.5]) rotate([0,0,20])
                                    cube([10,10,4], center=true);
                                mirror([0,1,0]) {
                                    translate([x-13,10,0.5]) rotate([0,0,120])
                                        cube([10,10,4], center=true);
                                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                                        cube([10,10,4], center=true);
                                }
                            }
                        }
                        
                        translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                            color(color) cube([4,2,4]);
                        }
                        mirror([0,1,0]) {
                            translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                color(color) cube([4,2,4]);
                            }
                        }
                    }
                }
                
                translate([-11,4,-6]) rotate([0,0,0])
                    color("#B8A693") cube([5,5,5]);
                mirror([0,1,0]) {
                    translate([-11,4,-6]) rotate([0,0,0]) {
                        color("#B8A693") cube([5,5,5]);
                    }
                }
            }
        }
    }
    
    difference() { // bottom cutout 
        translate([0.55,-0.01,-2.25]) scale([1.15,1.15,1.15]) {
            difference() {
                translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                    color("#B8A693") difference() {
                        color(color) cylinder(r=20, h=2, $fn=100);
                        translate([x+10,0,1])
                            cube([40,42,4], center=true);
                        translate([x-13,10,0.5]) rotate([0,0,120])
                            cube([10,10,4], center=true);
                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                            cube([10,10,4], center=true);
                        mirror([0,1,0]) {
                            translate([x-13,10,0.5]) rotate([0,0,120])
                                cube([10,10,4], center=true);
                            translate([x-7.26,7,0.5]) rotate([0,0,20])
                                cube([10,10,4], center=true);
                        }
                    }
                }
                
                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([4,2,4]);
                }
                mirror([0,1,0]) {
                    translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                        color("#B8A693") cube([4,2,4]);
                    }
                }
            }
        }
        translate([0.25,-0.01,-0.65]) scale([1.1,1.125,1]) {
            difference() {
                translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                    color("#B8A693") difference() {
                        cylinder(r=20, h=2, $fn=100);
                        translate([x+10,0,1])
                            cube([40,42,4], center=true);
                        translate([x-13,10,0.5]) rotate([0,0,120])
                            cube([10,10,4], center=true);
                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                            cube([10,10,4], center=true);
                        mirror([0,1,0]) {
                            translate([x-13,10,0.5]) rotate([0,0,120])
                                cube([10,10,4], center=true);
                            translate([x-7.26,7,0.5]) rotate([0,0,20])
                                cube([10,10,4], center=true);
                        }
                    }
                }
                
                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([4,2,4]);
                }
                mirror([0,1,0]) {
                    translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                        color("#B8A693") cube([4,2,4]);
                    }
                }
            }
        }
        difference() { // bottom green inside
            translate([0,-0.01,-3.1]) scale([1.1,1.125,1]) color(color){
                difference() {
                    translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                        color(color) difference() {
                            cylinder(r=20, h=2, $fn=100);
                            translate([x+10,0,1])
                                cube([40,42,4], center=true);
                            translate([x-13,10,0.5]) rotate([0,0,120])
                                cube([10,10,4], center=true);
                            translate([x-7.26,7,0.5]) rotate([0,0,20])
                                cube([10,10,4], center=true);
                            mirror([0,1,0]) {
                                translate([x-13,10,0.5]) rotate([0,0,120])
                                    cube([10,10,4], center=true);
                                translate([x-7.26,7,0.5]) rotate([0,0,20])
                                    cube([10,10,4], center=true);
                            }
                        }
                    }
                    
                    translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                        color(color) cube([4,2,4]);
                    }
                    mirror([0,1,0]) {
                        translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                            color(color) cube([4,2,4]);
                        }
                    }
                }
            }
            translate([0.2,-0.01,-2.8]) scale([1.1,1.125,1]) {
                difference() {
                    translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                        color(color) difference() {
                            cylinder(r=20, h=2, $fn=100);
                            translate([x+10,0,1])
                                cube([40,42,4], center=true);
                            translate([x-13,10,0.5]) rotate([0,0,120])
                                cube([10,10,4], center=true);
                            translate([x-7.26,7,0.5]) rotate([0,0,20])
                                cube([10,10,4], center=true);
                            mirror([0,1,0]) {
                                translate([x-13,10,0.5]) rotate([0,0,120])
                                    cube([10,10,4], center=true);
                                translate([x-7.26,7,0.5]) rotate([0,0,20])
                                    cube([10,10,4], center=true);
                            }
                        }
                    }
                    
                    translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                        color(color) cube([4,2,4]);
                    }
                    mirror([0,1,0]) {
                        translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                            color(color) cube([4,2,4]);
                        }
                    }
                }
            }
            
            translate([-11,4,-6]) rotate([0,0,0])
                color("#B8A693") cube([5,5,5]);
            mirror([0,1,0]) {
                translate([-11,4,-6]) rotate([0,0,0]) {
                    color("#B8A693") cube([5,5,5]);
                }
            }
        }
    } // left stairset
    translate([-8.1,-4.6,-3.64999]) rotate([0,0,-7.5]) for(i = [0:0.05:1.15]) {
        translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.4,0.05]);
    }
    translate([1.4,-0.3,-1.7]) {
        difference() {
            union() {
                translate([-8.8,-4.78,-3.35]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([0.6,0.8,0.9]);
                }
                translate([-8.8,-4.78,-3.195]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([0.6,0.12,0.9]);
                }
                translate([-8.6,-4.8,-3.12]) rotate([0,25,-7.5]) {
                    color("#B8A693") cube([2,0.12,0.9]);
                }
                translate([-8.57,-4.7,-3.26]) rotate([0,25,-7.5]) {
                color("#B8A693") cube([2,00.8,0.9]);
                }
            }
            translate([-8.8,-5.15,-3.3]) rotate([0,0,-7.5]) color("#B8A693") cube([0.4,0.5,0.5]);
        }
        translate([-8.75,-4.77,-2.8]) rotate([0,90,-7.5]) color("#B8A693") //entrance 2
            linear_extrude(height=0.4)
                rotate([0,0,-60]) circle(r=0.25, $fn=3);
    }
    translate([-6.79,-5.1,-4.2]) rotate([0,0,-7.5]) for(i = [0:0.05:1.85]) {
        translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.8,0.05]);
    } // right stairset
    mirror([0,1,0]) {
        translate([-8.1,-4.6,-3.64999]) rotate([0,0,-7.5]) for(i = [0:0.05:1.15]) {
            translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.4,0.05]);
        }
        translate([1.4,-0.3,-1.7]) {
            difference() {
                union() {
                    translate([-8.8,-4.78,-3.35]) rotate([0,0,-7.5]) {
                        color("#B8A693") cube([0.6,0.8,0.9]);
                    }
                    translate([-8.8,-4.78,-3.195]) rotate([0,0,-7.5]) {
                        color("#B8A693") cube([0.6,0.12,0.9]);
                    }
                    translate([-8.6,-4.8,-3.12]) rotate([0,25,-7.5]) {
                        color("#B8A693") cube([2,0.12,0.9]);
                    }
                    translate([-8.57,-4.7,-3.26]) rotate([0,25,-7.5]) {
                    color("#B8A693") cube([2,00.8,0.9]);
                    }
                }
                translate([-8.8,-5.15,-3.3]) rotate([0,0,-7.5]) color("#B8A693") cube([0.4,0.5,0.5]);
            }
            translate([-8.75,-4.77,-2.8]) rotate([0,90,-7.5]) color("#B8A693") //entrance 2
                linear_extrude(height=0.4)
                    rotate([0,0,-60]) circle(r=0.25, $fn=3);
        }
        translate([-6.79,-5.1,-4.2]) rotate([0,0,-7.5]) for(i = [0:0.05:1.85]) {
            translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.8,0.05]);
        }
    }
    // the triangle shaped roof at the front / top one
    rotate([0,0,-10])
        triangle();
    // bottom triangle roof thingy
    translate([-0.43,0,-0.8]) rotate([0,0,-10])
        triangle();
    translate([-3.25,4.86,-4.5]) rotate([0,90,7.5]) color("#B8A693") //window bottom
        linear_extrude(height=0.4)
            rotate([0,0,-60]) circle(r=0.25, $fn=3);
    translate([-3.25,4.86,-3.6]) rotate([0,90,7.5]) color("#B8A693") //window top
        linear_extrude(height=0.4)
            rotate([0,0,-60]) circle(r=0.25, $fn=3);
    
} 
module bottom_second_hall(x, depth) {
    difference() {
        translate([0,0,-8.5]) rotate([0,0,0]) color("#B8A693"){ // top floor
            translate([2.5,0,4.3]) rotate([0,15,0])
                cube([2, 10, 2], center=true);
                translate([-0.2,0,4.525]) rotate([0,0,0])
                    cube([4, 10, 2], center=true);
            difference() {
                union() {
                    translate([-2.9,0,5]) rotate([0,15,0])
                        cube([3.5, 10, 2], center=true);
                    translate([-5.825,0,5.425]) rotate([0,0,0])
                        cube([3, 10, 2], center=true);
                    translate([-7.35,-5,3])
                        cube([12,10,2]);
                }
                translate([-8,-6.3,2.5]) rotate([0,0,-7.5]) 
                    cube([7.5,2,4]);
                translate([-8,4.25,2.5]) rotate([0,0,7.5]) 
                    cube([7.5,2,4]);        
            }
        }
        translate([-3.38,4.8,-4]) rotate([0,0,7.5]) color(color) cube([1,0.3,0.2]); //window 1
        translate([-2.25,4.95,-4]) color(color) cube([2.5,0.3,0.2]); //window 2
        translate([-2.25,4.95,-4]) color(color) cube([2.5,0.3,0.2]); //window 3
    }
    translate([-2.25,5,-3.85]) rotate([0,90,]) color("#B8A693") //top window frame
        linear_extrude(height=2.5)
            rotate([0,0,-60]) circle(r=0.05, $fn=3);
    translate([-2.25,5,-4.03]) rotate([0,90,0]) color("#B8A693") //bottom window frame
        linear_extrude(height=2.5)
            rotate([0,0,-60]) circle(r=0.05, $fn=3);
    translate([-1.9,5,-3.5]) rotate([0,90,0]) color("#B8A693") //window
        linear_extrude(height=0.5)
            rotate([0,0,-60]) circle(r=0.3, $fn=3);
    translate([-2.8,4.95,-3.5]) rotate([0,90,7.5]) color("#B8A693") //window 2 -> on the right
        linear_extrude(height=0.25)
            rotate([0,0,-60]) circle(r=0.3, $fn=3);
    translate([0,-0.01,-1]) { // top floor
        difference() {
            translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                color("#B8A693") difference() {
                    cylinder(r=20, h=2, $fn=100);
                    translate([x+10,0,1])
                        cube([40,42,4], center=true);
                    translate([x-13,10,0.5]) rotate([0,0,120])
                        cube([10,10,4], center=true);
                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                        cube([10,10,4], center=true);
                    mirror([0,1,0]) {
                        translate([x-13,10,0.5]) rotate([0,0,120])
                            cube([10,10,4], center=true);
                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                            cube([10,10,4], center=true);
                    }
                }
            }
            
            translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                color("#B8A693") cube([4,2,4]);
            }
            mirror([0,1,0]) {
                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([4,2,4]);
                }
            }
            translate([-0.1,0,1.9]) scale([0.9,0.9,0.9]){
                difference() { // top green inside
                    translate([0,-0.01,-3.1]) scale([1.1,1.125,1]) {
                        difference() {
                            translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                                color(color) difference() {
                                    cylinder(r=20, h=2, $fn=100);
                                    translate([x+10,0,1])
                                        cube([40,42,4], center=true);
                                    translate([x-13,10,0.5]) rotate([0,0,120])
                                        cube([10,10,4], center=true);
                                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                                        cube([10,10,4], center=true);
                                    mirror([0,1,0]) {
                                        translate([x-13,10,0.5]) rotate([0,0,120])
                                            cube([10,10,4], center=true);
                                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                                            cube([10,10,4], center=true);
                                    }
                                }
                            }
                            
                            translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                color(color) cube([4,2,4]);
                            }
                            mirror([0,1,0]) {
                                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                    color(color) cube([4,2,4]);
                                }
                            }
                        }
                    }
                    translate([0.2,-0.01,-2.8]) scale([1.1,1.125,1]) {
                        difference() {
                            translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                                color(color) difference() {
                                    cylinder(r=20, h=2, $fn=100);
                                    translate([x+10,0,1])
                                        cube([40,42,4], center=true);
                                    translate([x-13,10,0.5]) rotate([0,0,120])
                                        cube([10,10,4], center=true);
                                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                                        cube([10,10,4], center=true);
                                    mirror([0,1,0]) {
                                        translate([x-13,10,0.5]) rotate([0,0,120])
                                            cube([10,10,4], center=true);
                                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                                            cube([10,10,4], center=true);
                                    }
                                }
                            }
                            
                            translate([-10,-5.25,-5]) rotate([0,0,-7.5]) {
                                color(color) cube([4,2,4]);
                            }
                            mirror([0,1,0]) {
                                translate([-10,-5.25,-5]) rotate([0,0,-7.5]) {
                                    color(color) cube([4,2,4]);
                                }
                            }
                        }
                    }
                    
                    translate([-11,4,-6]) rotate([0,0,0])
                        color("#B8A693") cube([5,5,5]);
                    mirror([0,1,0]) {
                        translate([-11,4,-6]) rotate([0,0,0]) {
                            color("#B8A693") cube([5,5,5]);
                        }
                    }
                }
            }
        }
    }
    translate([0.5,0,0.5]) {
        difference() { // bottom cutout 
            translate([0.55,-0.01,-2.25]) scale([1.15,1.15,1.15]) {
                difference() {
                    translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                        color("#B8A693") difference() {
                            color(color) cylinder(r=20, h=2, $fn=100);
                            translate([x+10,0,1])
                                cube([40,42,4], center=true);
                            translate([x-13,10,0.5]) rotate([0,0,120])
                                cube([10,10,4], center=true);
                            translate([x-7.26,7,0.5]) rotate([0,0,20])
                                cube([10,10,4], center=true);
                            mirror([0,1,0]) {
                                translate([x-13,10,0.5]) rotate([0,0,120])
                                    cube([10,10,4], center=true);
                                translate([x-7.26,7,0.5]) rotate([0,0,20])
                                    cube([10,10,4], center=true);
                            }
                        }
                    }
                    
                    translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                        color("#B8A693") cube([4,2,4]);
                    }
                    mirror([0,1,0]) {
                        translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                            color("#B8A693") cube([4,2,4]);
                        }
                    }
                }
            }
            translate([0.25,-0.01,-0.65]) scale([1.1,1.125,1]) {
                difference() {
                    translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                        color("#B8A693") difference() {
                            cylinder(r=20, h=2, $fn=100);
                            translate([x+10,0,1])
                                cube([40,42,4], center=true);
                            translate([x-13,10,0.5]) rotate([0,0,120])
                                cube([10,10,4], center=true);
                            translate([x-7.26,7,0.5]) rotate([0,0,20])
                                cube([10,10,4], center=true);
                            mirror([0,1,0]) {
                                translate([x-13,10,0.5]) rotate([0,0,120])
                                    cube([10,10,4], center=true);
                                translate([x-7.26,7,0.5]) rotate([0,0,20])
                                    cube([10,10,4], center=true);
                            }
                        }
                    }
                    
                    translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                        color("#B8A693") cube([4,2,4]);
                    }
                    mirror([0,1,0]) {
                        translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                            color("#B8A693") cube([4,2,4]);
                        }
                    }
                }
            }
            translate([0,0,-0.9]) {
                difference() { // bottom green inside
                    translate([0,-0.01,-3.1]) scale([1.1,1.125,1]) color(color){
                        difference() {
                            translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                                color(color) difference() {
                                    cylinder(r=20, h=2, $fn=100);
                                    translate([x+10,0,1])
                                        cube([40,42,4], center=true);
                                    translate([x-13,10,0.5]) rotate([0,0,120])
                                        cube([10,10,4], center=true);
                                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                                        cube([10,10,4], center=true);
                                    mirror([0,1,0]) {
                                        translate([x-13,10,0.5]) rotate([0,0,120])
                                            cube([10,10,4], center=true);
                                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                                            cube([10,10,4], center=true);
                                    }
                                }
                            }
                            
                            translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                color(color) cube([4,2,4]);
                            }
                            mirror([0,1,0]) {
                                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                    color(color) cube([4,2,4]);
                                }
                            }
                        }
                    }
                    translate([0.2,-0.01,-2.8]) scale([1.1,1.125,1]) {
                        difference() {
                            translate([x+16.75,0,-3.5]) rotate([0,0,0]) {
                                color(color) difference() {
                                    cylinder(r=20, h=2, $fn=100);
                                    translate([x+10,0,1])
                                        cube([40,42,4], center=true);
                                    translate([x-13,10,0.5]) rotate([0,0,120])
                                        cube([10,10,4], center=true);
                                    translate([x-7.26,7,0.5]) rotate([0,0,20])
                                        cube([10,10,4], center=true);
                                    mirror([0,1,0]) {
                                        translate([x-13,10,0.5]) rotate([0,0,120])
                                            cube([10,10,4], center=true);
                                        translate([x-7.26,7,0.5]) rotate([0,0,20])
                                            cube([10,10,4], center=true);
                                    }
                                }
                            }
                            
                            translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                color(color) cube([4,2,4]);
                            }
                            mirror([0,1,0]) {
                                translate([-10,-6.025,-5]) rotate([0,0,-7.5]) {
                                    color(color) cube([4,2,4]);
                                }
                            }
                        }
                    }
                    
                    translate([-11,4,-6]) rotate([0,0,0])
                        color("#B8A693") cube([5,5,5]);
                    mirror([0,1,0]) {
                        translate([-11,4,-6]) rotate([0,0,0]) {
                            color("#B8A693") cube([5,5,5]);
                        }
                    }
                }
            }
        }
    } 
    // left stairset
    //translate([-8.1,-4.6,-3.64999]) rotate([0,0,-7.5]) for(i = [0:0.05:1.15]) {
    //    translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.4,0.05]);
    //}
    translate([2.25,-0.25,0]) {
        translate([1.4,-0.3,-2.2]) {
            translate([-8.57,-4.7,-3.26]) rotate([0,25,-7.5]) {
                    color("#B8A693") cube([2,00.8,0.9]);
            }
            translate([-8.6,-4.8,-3.12]) rotate([0,25,-7.5]) {
                color("#B8A693") cube([2,0.12,0.9]);
            }
            translate([-8.8,-4.77,-3.35]) rotate([0,0,-7.5]) {
                color("#B8A693") cube([0.6,0.8,0.9]);
            }
            translate([-8.8,-4.77,-3.195]) rotate([0,0,-7.5]) {
                color("#B8A693") cube([0.6,0.12,0.9]);
            }
        }
        translate([-6.79,-5.1,-4.7]) rotate([0,0,-7.5]) for(i = [0:0.05:1.85]) {
            translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.8,0.05]);
        }
    }
    translate([0.25,0,0.8]) {
        translate([1.4,-0.3,-2.2]) {
            translate([-8.57,-4.7,-3.26]) rotate([0,25,-7.5]) {
                    color("#B8A693") cube([2,00.8,0.9]);
            }
            difference() {
                translate([-9.44,-4.67,-5]) rotate([0,25,-7.5]) {
                    color("#B8A693") cube([2,0.12,3]);
                }
                translate([-8.4,-5,-4.1]) color("#B8A693") rotate([0,0,-7.5]) cube([0.3,0.5,0.7]);
            }
            translate([-8.375,-4.78,-3.57]) rotate([0,90,-7.5]) color("#B8A693") //entrance
                linear_extrude(height=0.3)
                    rotate([0,0,-60]) circle(r=0.25, $fn=3);
            translate([-8.8,-4.75,-3.25]) rotate([0,0,-7.5]) {
                color("#B8A693") cube([0.6,0.8,0.9]);
            }
            translate([-8.7,-4.76,-3.1]) rotate([0,0,-7.5]) {
                color("#B8A693") cube([0.6,0.12,0.9]);
            }
        }
        translate([-6.79,-5.1,-4.7]) rotate([0,0,-7.5]) for(i = [0:0.05:1.85]) {
            translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.8,0.05]);
        }
    }
    // right stairset
    mirror([0,1,0]) {
        //translate([-8.1,-4.6,-3.64999]) rotate([0,0,-7.5]) for(i = [0:0.05:1.15]) {
        //    translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.4,0.05]);
        //}
        translate([2.25,-0.25,0]) {
            translate([1.4,-0.3,-2.2]) {
                translate([-8.57,-4.7,-3.26]) rotate([0,25,-7.5]) {
                        color("#B8A693") cube([2,00.8,0.9]);
                }
                translate([-8.6,-4.8,-3.12]) rotate([0,25,-7.5]) {
                    color("#B8A693") cube([2,0.12,0.9]);
                }
                translate([-8.8,-4.78,-3.35]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([0.6,0.8,0.9]);
                }
                translate([-8.8,-4.78,-3.195]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([0.6,0.12,0.9]);
                }
            }
            translate([-6.79,-5.1,-4.7]) rotate([0,0,-7.5]) for(i = [0:0.05:1.85]) {
                translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.8,0.05]);
            }
        }
        translate([0.25,0,0.8]) {
            translate([1.4,-0.3,-2.2]) {
                translate([-8.57,-4.7,-3.26]) rotate([0,25,-7.5]) {
                        color("#B8A693") cube([2,00.8,0.9]);
                }
                difference() {
                    translate([-9.44,-4.67,-5]) rotate([0,25,-7.5]) {
                        color("#B8A693") cube([2,0.12,3]);
                    }
                    translate([-7.9,-5,-4.1]) color("#B8A693") rotate([0,0,-7.5]) cube([0.3,0.5,0.7]);
                }
                translate([-7.875,-4.78,-3.57]) rotate([0,90,-7.5]) color("#B8A693") //entrance
                    linear_extrude(height=0.3)
                        rotate([0,0,-60]) circle(r=0.25, $fn=3);
                translate([-8.8,-4.76,-3.25]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([0.6,0.8,0.9]);
                }
                translate([-8.8,-4.76,-3.1]) rotate([0,0,-7.5]) {
                    color("#B8A693") cube([0.6,0.12,0.9]);
                }
            }
            translate([-6.79,-5.1,-4.7]) rotate([0,0,-7.5]) for(i = [0:0.05:1.85]) {
                translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,0.8,0.05]);
            }
        }
    }
    // the triangle shaped roof at the front / top one
    // rotate([0,0,-10])
    //    triangle();
    // bottom triangle roof thingy
    translate([0.07,0,-1.2]) rotate([0,0,-10])
        triangle();
} 
module ground() {
    difference() {
        translate([9.5,2.5,-6]) rotate([0,0,90]) //bottom plate
            color("#6D675A") cube([22.5,40,2], center=true);
        translate([-9,14,-6]) rotate([0,0,0]) 
            color("#6D675A") cube([6,6,3], center=true);
    }
    translate([-7,3,-7]) rotate([0,0,0]) //cylinder
        color("#6D675A") cylinder(h=2, r=10, $fn=100);
    translate([0,-4.45,-5.6]) rotate([0,0,0]) //ground plate 
        difference() {
            color("#B8A693") cube([15,17.75,2]);
            translate([0.05,17.7,1.6]) color(color) cube([6,0.3,0.15]); //window 1 -> right side
            translate([12,17.7,1.4]) color(color) cube([2.5,0.3,0.5]); //window 2 -> right side
            translate([11.8,17.7,0.9]) color(color) cube([1.8,0.3,0.1]); //window 3 -> right side
            translate([14.6,17.7,0.85]) color(color) cube([1,0.3,0.3]); //window 4 -> right side
            // -> window 4 in the bottom of the stairset
            translate([12.5,-0.1,1.5]) color(color) cube([2.3,0.15,0.1]); //window -> left side
            translate([3.7,-0.1,1.5]) color(color) cube([5,0.15,0.1]); //window 2 -> left side
        }
    translate([0.05,13.3,-3.85]) rotate([0,90,0]) color("#B8A693") //top window frame -> window 1
        linear_extrude(height=6)
            rotate([0,0,-60]) circle(r=0.05, $fn=3);
    translate([0.05,13.3,-4.03]) rotate([0,90,0]) color("#B8A693") //bottom window frame -> window 1
        linear_extrude(height=6)
            rotate([0,0,-60]) circle(r=0.05, $fn=3);
    translate([12,13.3,-3.85]) rotate([0,90,0]) color("#B8A693") //top window frame -> window 2
        linear_extrude(height=2.5)
            rotate([0,0,-60]) circle(r=0.15, $fn=3);
    translate([12,13.3,-4.25]) rotate([0,90,0]) color("#B8A693") //bottom window frame -> window 2
        linear_extrude(height=2.5)
            rotate([0,0,-60]) circle(r=0.05, $fn=3);
    translate([11.8,13.3,-4.575]) rotate([0,90,0]) color("#B8A693") //top window frame -> window 3
        linear_extrude(height=1.8)
            rotate([0,0,-60]) circle(r=0.05, $fn=3);
    translate([11.8,13.3,-4.75]) rotate([0,90,0]) color("#B8A693") //bottom window frame -> window 3
        linear_extrude(height=1.8)
            rotate([0,0,-60]) circle(r=0.05, $fn=3);
     translate([14.6,13.3,-4.44]) rotate([0,90,0]) color("#B8A693") //top window frame -> window 4
        linear_extrude(height=1.8)
            rotate([0,0,-60]) circle(r=0.15, $fn=3);
    translate([14.6,13.3,-4.8]) rotate([0,90,0]) color("#B8A693") //bottom window frame -> window 4
        linear_extrude(height=1.8)
            rotate([0,0,-60]) circle(r=0.05, $fn=3);
    translate([0,-4.45,-3.6]) rotate([0,0,0]) //ground plate / top part
        color("#6D675A") cube([15,17.75,0.1]);
    translate([-8,12.1,-6]) rotate([0,0,24]) //cylinder addon
        color("#6D675A") cube([6,2.5,2], center=true);
    translate([-3.725,13,-6]) rotate([0,0,0]) //ground plate addon
        color("#6D675A") cube([7.5,4,2], center=true);
    translate([4.7,12.365,-6]) rotate([0,0,-7.5]) //ground plate addon
        color("#6D675A") cube([10,4,2], center=true);
    translate([15,6.3,-3.55]) rotate([0,0,0]) { //stairsset -> second hall
        for(i = [0:0.05:0.7]) {
            translate([0+i,0,0-i/3]) color("#B8A693") cube([0.05,7,0.05]);
        }
        translate([0.7,0,-0.7/3])
            color("#B8A693") cube([0.25,7,0.05]);
        translate([0.7+0.25,0,-0.7/3]) {
            for(i = [0:0.05:0.7]) {
                translate([0+i,0,0-i/3]) color("#B8A693") cube([0.05,7,0.05]);
            }
        } 
        if (lagfree==false) {
            difference() { //fill -> under stairs
                translate([0,0,-0.6]) color("#B8A693") cube([1.7,7,0.7]);
                for(i = [0:0.05:0.7]) {
                    translate([-0.01+i,-0.1,0-i/3]) color("#B8A693") cube([0.06,7.2,1]);
                }
                translate([0.7,-0.1,-0.7/3])
                    color("#B8A693") cube([0.26,7.2,1]);
                translate([0.7+0.25,-0.1,-0.7/3]) {
                    for(i = [0:0.05:0.7]) {
                        translate([0+i,0,0-i/3]) color("#B8A693") cube([0.06,7.2,1]);
                    }
                }    
            }
        }
    }  
    translate([-0.65,5.5,-4.45]) //transition between the two halls in the middle
        color("#B8A693") cube([2.5,3,3], center=true);
    translate([-1.9,7,-3.5]) rotate([0,-90,90]) //triangle roof thingy -> transition
        color("#B8A693")
        linear_extrude(height=3)
            circle(r=0.5, $fn=3);
    translate([0.6,4,-3]) for(i = [0:0.05:1.85]) //stairs back -> transition
            translate([0+i,0,0-i/2.2]) color("#B8A693") cube([0.05,3,0.05]);
    fence(); //fencing in the transition
    translate([17.5,11.55,-4.05]) rotate([0,0,0]) { //stairsset -> right down
        for(i = [0:0.05:0.8]) {
            translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.05,1.75,0.05]);
        }
        translate([0.8,0,-0.8/3])
            color("#C0C0C0") cube([0.25,1.75,0.05]);
        translate([0.8+0.25,0,-0.8/3]) {
            for(i = [0:0.05:0.8]) {
                translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.05,1.75,0.05]);
            }
        }
        translate([1.6+0.25,0,-1.6/3])
            color("#C0C0C0") cube([0.25,1.75,0.05]);
        translate([1.6+0.45,0,-1.6/3]) {
            for(i = [0:0.05:1.35]) {
                translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.05,1.75,0.05]);
            }
        }
        if (lagfree==false) {
            difference() {
                translate([0,0,-1]) color("#C0C0C0") cube([4,1.75,1.2]);
                color("#C0C0C0") union() {
                    translate([-1,-0.01,0.37]) rotate([0,19,0]) cube([2,1.78,1]);
                    translate([0.9,-0.01,-0.23]) rotate([0,0,0]) cube([2,1.78,1]);
                    translate([2.1,-0.01,-0.23]) rotate([0,0,0]) cube([2,1.78,1]);
                    translate([0,-0.01,0.15]) rotate([0,19,0]) cube([2,1.78,1]);
                    translate([1.9,-0.01,-0.5]) rotate([0,0,0]) cube([2.5,1.78,1]);
                    translate([2.1,-0.01,-0.5]) rotate([0,19,0]) cube([2,1.78,1]);
                }
            }
        }
    }
    translate([15,-4.45,-4.2]) { //lower ground plate
        difference() {
            union() {
                difference() {
                    color("#C0C0C0") cube([8,17.75,0.18]);
                    translate([-0.2,-0.2,-0.01]) cube([2.74,19,0.2]);
                }
                translate([0,0,0.18]) //lower ground plate top part
                    color("#6D675A") cube([8,17.75,0.02]);
            }
            translate([2.5,16,-0.1]) color("#C0C0C0") cube([7,2,0.4]);
        }
        difference() {
            translate([-0.2,0,-0.9]) color("#B8A693") cube([2.74,17.75,1.09]);
            translate([-0.4,17.7,-0.55]) color(color) cube([1.8,0.3,0.3]); //window 4 -> right side
        }
    }
    translate([23,-4.45,-4.05]) rotate([0,0,0]) { //stairsset -> most back
        for(i = [0:0.05:0.8]) {
            translate([0+i,0,0-i/3]) color("#B8A693") cube([0.05,16,0.05]);
        }
        translate([0.8,0,-0.8/3])
            color("#B8A693") cube([0.25,16,0.05]);
        translate([0.8+0.25,0,-0.8/3]) {
            for(i = [0:0.05:0.8]) {
                translate([0+i,0,0-i/3]) color("#B8A693") cube([0.05,16,0.05]);
            }
        }
        translate([1.6+0.25,0,-1.6/3])
            color("#B8A693") cube([0.25,16,0.05]);
        translate([1.6+0.45,0,-1.6/3]) {
            for(i = [0:0.05:1.35]) {
                translate([0+i,0,0-i/3]) color("#B8A693") cube([0.05,16,0.05]);
            }
        }
        if (lagfree==false) { //fill -> stairset -> most back
            color("#B8A693") difference() {
                translate([0,0,-1]) cube([3.4,16,1.1]);
                for(i = [0:0.05:0.8]) {
                    translate([-0.01+i,-0.1,0-i/3]) color("#B8A693") cube([0.06,16.2,2]);
                }
                translate([0.8,-0.1,-0.8/3])
                    color("#B8A693") cube([0.26,16.2,2]);
                translate([0.8+0.25,-0.1,-0.8/3]) {
                    for(i = [0:0.05:0.8]) {
                        translate([0+i,0,0-i/3]) color("#B8A693") cube([0.06,16.2,2]);
                    }
                }
                translate([1.6+0.25,-0.1,-1.6/3])
                    color("#B8A693") cube([0.26,16.2,2]);
                translate([1.6+0.45,-0.1,-1.6/3]) {
                    for(i = [0:0.05:1.35]) {
                        translate([0+i,0,0-i/3]) color("#B8A693") cube([0.06,16.2,2]);
                    }
                }
                translate([-0.5,-0.1,-1.04]) rotate([0,19,0])
                    cube([4,16.2,1]);
            }
        }
    }
    translate([15,3.9,-4.3]) { // transition between stairsets -> middle
        color("#B8A693") translate([0.065,0,1]) rotate([-90,60,0]) linear_extrude(height=2.5)
            circle(r=0.07, $fn=3);
        color("#B8A693") cube([0.1,2.5,1]);
    }
    translate([15.8,-4.449,-3.55]) color("#B8A693") scale([1,0.6,1]) { //stairsset -> left hall
        for(i = [0:0.05:0.7]) {
            translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.05,7,0.05]);
        }
        translate([0.7,0,-0.7/3])
            color("#C0C0C0") cube([0.25,7,0.05]);
        translate([0.7+0.25,0,-0.7/3]) {
            for(i = [0:0.05:0.7]) {
                translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.05,7,0.05]);
            }
        } 
        if (lagfree==false) {
            difference() { //fill -> under stairs
                translate([0,0,-0.6]) color("#C0C0C0") cube([1.7,7,0.7]);
                for(i = [0:0.05:0.7]) {
                    translate([-0.01+i,-0.1,0-i/3]) color("#C0C0C0") cube([0.06,7.2,1]);
                }
                translate([0.7,-0.1,-0.7/3])
                    color("#C0C0C0") cube([0.26,7.2,1]);
                translate([0.7+0.25,-0.1,-0.7/3]) {
                    for(i = [0:0.05:0.7]) {
                        translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.06,7.2,1]);
                    }
                }    
            }
        }
        translate([-0.8,0,-0.5]) color("#B8A693") cube([0.8,7,0.5]);
    }
    translate([15.8,-0.3,-3.55]) scale([1,0.65,1]) { //stairsset -> middle
        for(i = [0:0.05:0.7]) {
            translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.05,7,0.05]);
        }
        translate([0.7,0,-0.7/3])
            color("#C0C0C0") cube([0.25,7,0.05]);
        translate([0.7+0.25,0,-0.7/3]) {
            for(i = [0:0.05:0.7]) {
                translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.05,7,0.05]);
            }
        } 
        if (lagfree==false) {
            difference() { //fill -> under stairs
                translate([0,0,-0.6]) color("#C0C0C0") cube([1.7,7,0.7]);
                for(i = [0:0.05:0.7]) {
                    translate([-0.01+i,-0.1,0-i/3]) color("#C0C0C0") cube([0.06,7.2,1]);
                }
                translate([0.7,-0.1,-0.7/3])
                    color("#C0C0C0") cube([0.26,7.2,1]);
                translate([0.7+0.25,-0.1,-0.7/3]) {
                    for(i = [0:0.05:0.7]) {
                        translate([0+i,0,0-i/3]) color("#C0C0C0") cube([0.06,7.2,1]);
                    }
                }    
            }
        }
        translate([-0.8,0,-0.5]) color("#C0C0C0") cube([0.8,7,0.5]);
    }
    translate([15,-4.45,-3.6]) //filling plate between the stairs and the main halls
        color("#6D675A") cube([0.8,8.7,0.1]);
    translate([15,-4.1,-4]) { //platform infront of stairs
        difference() {
            color("#6D675A") cube([7,6.5,0.2]);
            translate([5.4,-0.6,-0.1])
                color("#6D675A") cube([2.3,1.5,0.4]);
        }
    }
    translate([20.5,-3.2,-3.9]) rotate([0,0,-90]) {
        for(i = [0:0.05:0.55]) { //stairs at platform
            translate([-0.01+i,-0.1,0-i/3]) color("#B8A693") cube([0.06,1.6+i,0.1]);
        }
    }
    translate([22,-1.75,-3.9]) rotate([0,0,0]) mirror([0,1,0]) {
        for(i = [0:0.05:0.55]) { //stairs at platform
            translate([-0.01+i,-0.1,0-i/3]) color("#B8A693") cube([0.06,1.6+i,0.1]);
        }
    }
    translate([22,-1.75,-3.9]) {
        for(i = [0:0.05:0.55]) { //stairs at platform
            translate([-0.01+i,-0.1,0-i/3]) color("#B8A693") cube([0.06,4.25+i,0.1]);
        }
    }
    translate([20.55,2.4,-3.9]) rotate([0,0,-90]) mirror([1,0,0]) {
        for(i = [0:0.05:0.55]) { //stairs at platform
            translate([-0.01+i,-0.1,0-i/3]) color("#B8A693") cube([0.06,1.6+i,0.1]);
        }
    }
    translate([21,2.4,-3.9]) rotate([0,0,90]) {
        for(i = [0:0.05:0.55]) { //stairs at platform
            translate([-0.01+i,-0.1,0-i/3]) color("#B8A693") cube([0.06,4.2-i,0.1]);
        }
    }
    translate([0.2,0,-0.4])
        ohall();
}
module hall1() {
    difference() {
        roof();
        translate([0,0,-8.5]) rotate([0,0,0]) {
            cube([30,20,10], center=true);
            translate([2.5,0,4.3]) rotate([0,15,0])
                cube([2, 20, 2], center=true);
            translate([-3.2,0,4.525]) rotate([0,0,0])
                cube([10, 20, 2], center=true);
            translate([-2.9,0,5]) rotate([0,15,0])
                cube([3.5, 20, 2], center=true);
            translate([-5.825,0,5.425]) rotate([0,0,0])
                cube([3, 20, 2], center=true);
        }
    } 
    difference() {
        bottom(-6,1);
        translate([0,3.1,-4.5]) //adjust for stairs
            cube([5,2,2]);
    }
    intersection() { //back shell inside
        binside(10);
        translate([14,0,-6]) scale([0.89,0.79,0.89])
            balls(10);
    }
}
module hall2() {
    difference() {
        roof();
        translate([0,0,-8.5]) rotate([0,0,0]) {
            cube([30,20,10], center=true);
            translate([2.5,0,4.3]) rotate([0,15,0])
                cube([2, 20, 2], center=true);
            translate([-3.2,0,4.525]) rotate([0,0,0])
                cube([10, 20, 2], center=true);
            translate([-2.9,0,5]) rotate([0,15,0])
                cube([3.5, 20, 2], center=true);
            translate([-5.825,0,5.425]) rotate([0,0,0])
                cube([3, 20, 2], center=true);
        }
    } 
    bottom_second_hall(-6,1);
    intersection() { //back shell inside
        binside_second_hall(10);
        translate([14,0,-6]) scale([0.89,0.79,0.89])
            balls(10);
    }
}

module hall3() {
    difference() {
        union() {
            translate([14,-2,-4]) scale([0.35,0.35,0.35]) rotate([0,-5,0]) {
                difference() { //front shell
                    color(color2) shell1(radiuss1);
                    cutout(radiuss1-0.75);
                    mirror([0,1,0]) {
                        cutout(radiuss1-0.75);
                    }
                }
            }
            translate([18.6,-2,-4]) scale([0.35,0.35,0.35]) rotate([0,15,0]) mirror([1,0,0]) {
                difference() { //back shell
                    color(color2) shell1(radiuss1);
                    cutout(radiuss1-0.75);
                    mirror([0,1,0]) {
                        cutout(radiuss1-0.75);
                    }
                }
            }
            translate([17.6,-2.1,-2.45]) scale([0.35,0.35,0.35]) rotate([0,0,-5]) //left transition
                color(color2) transition();
            translate([17.6,-1.9,-2.45]) scale([0.35,0.35,0.35]) rotate([0,0,5]) mirror([0,1,0]) //right transition
                color(color2) transition();
            translate([-1,0.2,0.5]) scale([1.1,1.1,1.1]) //front shell inside
                h3inside();
            translate([38.1,0.2,0.2]) scale([1.4,1.1,1.1]) mirror([1,0,0]) //back shell inside
                h3inside();
        }
        translate([13,-5,-6.1]) cube([7,7,2]); //cutoff below
    }
}
//
// Spawn the Sydney Opera House
//
rotate([0,0,10]) //first hall -> most left
    hall1();
rotate([0,0,-10]) translate([-2.5,9.5,-1.2]) scale([0.7,0.7,0.7]) //second hall -> most right
    hall2();
translate([-0.6,0.7,0.4]) scale([1.1,1.1,1.1]) //third hall -> small in the back
    hall3();
ground(); //ground / floor
//
// You´ve reached the End :)
//